### ISSUE TITLE
Story #12

### ISSUE THREAD

**Issue by phisaz** [phisaz/SE-2-class#3]
As an administrator I want to list history of purchases So that I can compute statistics

**Comment by phisaz** [comment]
**Description**
---
Statistics include:
a) total value of purchases/sales after selecting a user, item or supplier
b) as above, including choice of time period of max 2 years
c) average values for a) and b)
d) comparison of max 3 users/items/suppliers
e) ranking for a), b) and c)

** TASKS LIST**
---
- [ ] design and implement statistics page with filters [Est.  2 days]
- [ ] build query and visualization for a) [Est. 4 hours]
- [ ] build time selection window and query for point b) [Est. 4 hours]
- [ ] implement query for c) and selection window [Est. 2 hours]
- [ ] design and implement page for hosting results for d) [Est. 1 day]
- [ ] implement ranking [Est. 4 hours]
- [ ] check permissions to enter the section [Est. 1 hour]
